version: '3.8'

services:
  # 1. Gateway Service
  gateway:
    image: node:18-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - public_net
      - service_net
    environment:
      - PORT=8080
    volumes:
      - ./gateway:/app

  # 2. Auth Service (Keycloak)
  auth:
    image: quay.io/keycloak/keycloak:22.0.0
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    networks:
      - public_net
      - service_net
    volumes:
      - ./auth/data:/opt/keycloak/data
      - ./auth/realm.json:/opt/keycloak/data/import/realm.json

  # 3. User Service
  users:
    image: node:18-alpine
    deploy:
      replicas: 1
    networks:
      - service_net
      - db_net
    volumes:
      - ./users:/app

  # 4. Challenges Service
  challenges:
    image: node:18-alpine
    deploy:
      replicas: 1
    networks:
      - service_net
      - db_net
    volumes:
      - ./challenges:/app

  # 5. Sandbox Runner Service (Replicated)
  sandbox-runner:
    image: python:3.9-slim
    build: ./sandbox-runner
    deploy:
      replicas: 2
    environment:
      - RABBITMQ_URL=amqp://user:password@broker:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/coding_challenges
    networks:
      - service_net
      - broker_net
      - db_net
    volumes:
      - ./sandbox-runner:/app

  # 6. Frontend
  frontend:
    image: node:18-alpine
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
    networks:
      - public_net
    volumes:
      - ./frontend:/app

  # 7. Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coding_challenges
    networks:
      - db_net
    volumes:
      - db_data:/var/lib/postgresql/data

  # 8. Broker (RabbitMQ)
  broker:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"
    networks:
      - broker_net

  # 9. Redis (for Rate Limiting)
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispassword
    networks:
      - service_net

networks:
  public_net:
    driver: overlay
  service_net:
    driver: overlay
    internal: true
  db_net:
    driver: overlay
    internal: true
  broker_net:
    driver: overlay
    internal: true

volumes:
  db_data:
