services:
  # 1. Gateway Service
  gateway:
    image: coding-challenges/gateway:latest
    build: ./gateway
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./gateway:/app

    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - public_net
      - service_net
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redispassword
      - AUTH_SERVICE_URL=http://auth:8080
      - USERS_SERVICE_URL=http://users:3000
      - CHALLENGES_SERVICE_URL=http://challenges:3000

  # 2. Auth Service (Keycloak)
  auth:
    image: quay.io/keycloak/keycloak:22.0.0
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_URL=http://localhost:8081

    ports:
      - "8081:8080"
    networks:
      - public_net
      - service_net
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./auth/realm.json:/opt/keycloak/data/import/realm.json

  # 3. User Service
  users:
    image: coding-challenges/users:latest
    build: ./users
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - ./users:/app

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/coding_challenges
      - KEYCLOAK_SERVER_URL=http://auth:8080/
      - KEYCLOAK_REALM=coding-challenges
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - service_net
      - db_net

  # 4. Challenges Service
  challenges:
    image: coding-challenges/challenges:latest
    build: ./challenges
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - ./challenges:/app

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/coding_challenges
      - RABBITMQ_URL=amqp://user:password@broker:5672
    networks:
      - service_net
      - db_net
      - broker_net

  # 5. Sandbox Runner Service (Replicated)
  sandbox-runner:
    image: coding-challenges/sandbox-runner:latest
    build: ./sandbox-runner
    deploy:
      replicas: 3
    volumes:
      - ./sandbox-runner:/app
    environment:
      - RABBITMQ_URL=amqp://user:password@broker:5672
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/coding_challenges
    networks:
      - service_net
      - broker_net
      - db_net

  # 6. Frontend
  frontend:
    image: coding-challenges/frontend:latest
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
    environment:
      - KEYCLOAK_CLIENT_ID=frontend-client
      - KEYCLOAK_CLIENT_SECRET=
      - KEYCLOAK_ISSUER=http://auth:8080/realms/coding-challenges
      - KEYCLOAK_EXTERNAL_ISSUER=http://localhost:8081/realms/coding-challenges
      - KEYCLOAK_URL=http://auth:8080
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=supersecret
    networks:
      - public_net

  # 7. Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    deploy:
      replicas: 1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coding_challenges
    networks:
      - db_net
    volumes:
      - db_data:/var/lib/postgresql/data

  # 8. Redis
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispassword
    deploy:
      replicas: 1
    networks:
      - service_net
    volumes:
      - redis_data:/data

  # 9. Message Broker (RabbitMQ)
  broker:
    image: rabbitmq:3-management-alpine
    deploy:
      replicas: 1
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"
    networks:
      - broker_net

networks:
  public_net:
    driver: overlay
  service_net:
    driver: overlay
    internal: true
  db_net:
    driver: overlay
    internal: true
  broker_net:
    driver: overlay
    internal: true

volumes:
  db_data:
  redis_data:
  keycloak_data:
